import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { assembleProject } from '../src/assembler.js';
import { tempDir, writeContracts } from '../test-support/helpers.js';

test('assembler can seed from a checked-out official upstream template before B2C overlays', async () => {
  const root = await tempDir();
  const contracts = path.join(root, 'contracts');
  const upstreamBase = path.join(root, 'upstream-base');
  const output = path.join(root, 'generated');
  await writeContracts(contracts);
  await mkdir(upstreamBase, { recursive: true });
  await writeFile(path.join(upstreamBase, 'UPSTREAM_BASE.txt'), 'cloudflare/templates@pinned\n');
  const result = await assembleProject(contracts, output, { baseTemplateDir: upstreamBase });
  assert.equal(result.baseTemplateDir, upstreamBase);
  assert.equal(await readFile(path.join(output, 'UPSTREAM_BASE.txt'), 'utf8'), 'cloudflare/templates@pinned\n');
  const app = await readFile(path.join(output, 'src/react/App.tsx'), 'utf8');
  assert.match(app, /Primary journey/);
  assert.match(app, /React UX approval workspace/);
  assert.doesNotMatch(app, /Generated by SaaS Harness/);
});
