import { workflowArtifactFiles } from './artifact-templates.js';
import { MODULES } from './registry.js';

function tsString(value) {
  return JSON.stringify(value, null, 2);
}

const PLATFORM_IMPLEMENTATIONS = new Set([
  'identity',
  'analytics',
  'admin-support',
  'privacy',
  'audit',
  'observability',
  'release-support',
  'order',
  'billing',
  'subscription',
  'entitlement',
  'credits',
]);

function moduleFile(name) {
  const metadata = MODULES[name] ?? { version: 'unregistered', status: 'unregistered' };
  return `/**
 * Generated boundary for an optional module that has no reusable runtime pack.
 * Production promotion remains blocked until this file is replaced by a tested
 * implementation and the module registry status becomes implemented.
 */
export const moduleStatus = ${JSON.stringify({
    name,
    version: metadata.version,
    status: metadata.status,
  }, null, 2)} as const;
`;
}

export function starterFiles(plan, contractRaw) {
  const packageJson = {
    name: plan.product.name,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc -b && vite build',
      preview: 'npm run build && vite preview',
      deploy: 'npm run build && wrangler deploy',
      check: 'tsc -b && vite build && wrangler deploy --dry-run',
      test: 'vitest run --config vitest.config.ts',
    },
    dependencies: { hono: '4.13.0', react: '19.2.1', 'react-dom': '19.2.1' },
    devDependencies: {
      '@cloudflare/vite-plugin': '1.15.3',
      '@types/node': '24.10.1',
      '@types/react': '19.2.7',
      '@types/react-dom': '19.2.3',
      '@vitejs/plugin-react': '5.1.1',
      typescript: '5.9.3',
      vite: '^7.0.0',
      vitest: '^4.1.0',
      wrangler: '4.88.0',
    },
  };

  const files = {
    'package.json': `${JSON.stringify(packageJson, null, 2)}\n`,
    '.gitignore': [
      'node_modules/',
      'dist/',
      '.wrangler/',
      '.dev.vars',
      '.env*',
      '!.env.example',
      'playwright-report/',
      'test-results/',
      '.impeccable/config.local.json',
      '.impeccable/hook.cache.json',
      '.impeccable/hook.pending.json',
      '.saasharness/runs/',
      '',
    ].join('\n'),
    'index.html': '<!doctype html>\n<html lang="en">\n  <head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="color-scheme" content="light dark" /><title>SaaS Harness</title></head>\n  <body><div id="root"></div><script type="module" src="/src/react/main.tsx"></script></body>\n</html>\n',
    'vite.config.ts': "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nimport { cloudflare } from '@cloudflare/vite-plugin';\n\nexport default defineConfig({ plugins: [react(), cloudflare()] });\n",
    'tsconfig.json': `${JSON.stringify({
      files: [],
      references: [{ path: './tsconfig.app.json' }, { path: './tsconfig.worker.json' }],
    }, null, 2)}\n`,
    'src/react/App.tsx': `import { runtimeConfig } from '../generated/runtime-config';

export function App() {
  return (
    <main className="shell">
      <p className="eyebrow">Generated by SaaS Harness</p>
      <h1>${plan.product.name}</h1>
      <p>Primary journey: <strong>{runtimeConfig.journey}</strong></p>
      <p>Current feature: <strong>{runtimeConfig.feature.name}</strong></p>
      <nav className="fixture-nav" aria-label="Product workspaces">
        <a href="/__ux">React UX approval workspace</a>
        <a href="/__admin">Admin and support console</a>
      </nav>
      {!runtimeConfig.codeReady && (
        <aside role="alert">
          A selected optional module has no implementation pack. Review <code>.saasharness/plan.json</code>.
        </aside>
      )}
      {runtimeConfig.codeReady && !runtimeConfig.productionReady && (
        <aside role="status">
          The reusable code path is assembled. Production remains gated on real provider, staging, migration, recovery, and human release evidence.
        </aside>
      )}
    </main>
  );
}
`,
    'src/react/ux-lab/fixtures.ts': `export const fixtures = {
  default: { state: 'ready', title: ${JSON.stringify(plan.feature.name)}, message: 'Replace this fixture with realistic product data.' },
  loading: { state: 'loading', title: 'Loading', message: 'The user must receive immediate feedback.' },
  empty: { state: 'empty', title: 'No data yet', message: 'Explain the first useful action.' },
  error: { state: 'error', title: 'Something went wrong', message: 'Provide recovery and preserve user work.' },
  permission: { state: 'permission', title: 'Permission required', message: 'Explain why access is needed and how to recover.' },
  paidLimit: { state: 'paid-limit', title: 'Plan limit reached', message: 'Explain price, entitlement, and next action clearly.' },
  delayed: { state: 'delayed', title: 'Still working', message: 'Preserve progress and make cancellation or return safe.' },
} as const;
`,
    'src/react/styles.css': ':root { font-family: Inter, ui-sans-serif, system-ui, sans-serif; color: #172b4d; background: #f7f8fa; }\nbody { margin: 0; min-width: 320px; }\na { color: inherit; }\n.shell { max-width: 68rem; margin: 0 auto; padding: clamp(2rem, 8vw, 7rem) 1.25rem; }\n.eyebrow { text-transform: uppercase; letter-spacing: .12em; font-size: .75rem; }\naside { margin-top: 2rem; padding: 1rem; border: 1px solid #d0d5dd; border-radius: .75rem; background: #fff; }\n.fixture-nav { display: flex; flex-wrap: wrap; gap: 1rem; margin: 1.5rem 0; }\n.fixture-nav button { min-height: 44px; padding: .65rem .9rem; }\ninput, button { font: inherit; }\n',
    'src/generated/runtime-config.ts': `export const runtimeConfig = ${tsString({
      profileHash: plan.profileHash,
      codeReady: plan.codeReady,
      productionReady: plan.productionReady,
      releaseEvidence: plan.releaseEvidence,
      journey: plan.ux.journey,
      feature: plan.feature,
      region: plan.product.region,
      monetization: plan.product.monetization,
      paymentProvider: plan.product.paymentProvider,
      database: plan.product.database,
      modules: plan.modules,
      cloudflare: plan.cloudflare,
    })} as const;\n`,
    '.saasharness/plan.json': `${JSON.stringify(plan, null, 2)}\n`,
    'module-lock.json': `${JSON.stringify(plan.moduleLock, null, 2)}\n`,
    'contracts/product.yml': contractRaw.product,
    'contracts/ux.yml': contractRaw.ux,
    'contracts/feature.yml': contractRaw.feature,
    'docs/architecture.md': `# Generated Architecture

- Profile hash: \`${plan.profileHash}\`
- Region: \`${plan.product.region}\`
- Database: \`${plan.moduleLock.adapters.database.provider}\`
- Payment: \`${plan.product.paymentProvider ?? 'none'}\`
- Modules: ${plan.modules.map((module) => `\`${module}\``).join(', ')}
- Cloudflare services: ${plan.cloudflare.map((service) => `\`${service}\``).join(', ')}
- Reusable code ready: **${plan.codeReady ? 'yes' : 'no'}**
- Production evidence complete: **${plan.productionReady ? 'yes' : 'no'}**

## Boundaries

Product features import module \`public.ts\` files only. Provider transports and protected persistence remain private to their owner module.

## Required release evidence

${plan.releaseEvidence.map((item) => `- ${item}`).join('\n')}

## Findings

${plan.warnings.length ? plan.warnings.map((warning) => `- **${warning.code}** (${warning.severity}): ${warning.message}`).join('\n') : '- None'}
`,
    'AGENTS.md': `# Generated project rules

1. Follow the stage order in \`.saasharness/workflow.json\`.
2. Product documents, IA/UX, architecture, plan, implementation, and release require independent critic channels and explicit human approval.
3. UX critics inspect a running React mock; source-only UX approval is invalid.
4. Work on one releasable feature slice at a time.
5. Use RED → GREEN → REFACTOR for domain, API, data, auth, billing, permissions, credits, privacy, and observable React behavior.
6. Use scenario-first tests for complete user journeys.
7. Product features import module public APIs only. Never access provider SDKs or protected tables directly.
8. Do not weaken tests, critic evidence, migrations, or release controls to obtain GREEN/PASS.
9. Use risk-routed verification. Billing, auth, privacy, credits, and migrations always run critical checks.
10. Reusable code readiness and production evidence are separate. Production requires provider sandbox evidence, staging, migration/recovery rehearsal, critic PASS, and human approval.
`,
    '.github/workflows/ci.yml': `name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run verify:critical
`,
    'THIRD_PARTY_NOTICES.md': `# Third-party sources

The generated project contains attributed ports and installed integrations from pinned commits listed in \`.saasharness/upstreams.lock.json\`.

- GitHub Spec Kit (MIT): constitution/spec/plan/tasks lifecycle through the official CLI and B2C preset.
- obra/superpowers (MIT): RED–GREEN–REFACTOR, worktree, task execution, debugging, review, and completion skills.
- Open Design (Apache-2.0): running design artifact and MCP workflow.
- Impeccable (Apache-2.0): design critique, audit, hardening, motion, and browser evidence.
- nikandr-surkov/ai-saas-starter (MIT): credits ledger, idempotency collision, conditional spend, and refund invariants ported to D1/PostgreSQL.
- wasp-lang/open-saas (MIT): Stripe checkout, portal, subscription lifecycle, webhook, and SaaS operational coverage ported to Cloudflare.
- Cloudflare templates/workers-sdk (Apache-2.0): React/Vite/Hono/Workers seed, Hyperdrive, D1 migration, and Workers Vitest patterns.

Preserve this file and the root repository's third-party notices when distributing generated code.
`,
    ...workflowArtifactFiles(plan),
  };

  for (const moduleName of plan.modules) {
    if (!PLATFORM_IMPLEMENTATIONS.has(moduleName)) {
      files[`src/modules/${moduleName}/public.ts`] = moduleFile(moduleName);
    }
  }
  return files;
}
