function tsString(value) {
  return JSON.stringify(value, null, 2);
}

function moduleFile(name) {
  return `/**\n * ${name} module public boundary.\n *\n * v0.1 is a generated contract boundary, not a production provider implementation.\n * Product features may import this file, but must not access provider SDKs or protected tables directly.\n */\nexport const moduleStatus = ${JSON.stringify({ name, status: 'contract-only' }, null, 2)} as const;\n`;
}

export function starterFiles(plan, contractRaw) {
  const packageJson = {
    name: plan.product.name,
    private: true,
    version: '0.0.0',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc -b && vite build',
      preview: 'npm run build && vite preview',
      deploy: 'npm run build && wrangler deploy',
      check: 'tsc -b && vite build && wrangler deploy --dry-run',
      test: 'vitest run',
    },
    dependencies: { hono: '4.11.1', react: '19.2.1', 'react-dom': '19.2.1' },
    devDependencies: {
      '@cloudflare/vite-plugin': '1.15.3',
      '@types/node': '24.10.1',
      '@types/react': '19.2.7',
      '@types/react-dom': '19.2.3',
      '@vitejs/plugin-react': '5.1.1',
      typescript: '5.9.3',
      vite: '^7.0.0',
      vitest: '4.0.14',
      wrangler: '4.88.0',
    },
  };

  const files = {
    'package.json': `${JSON.stringify(packageJson, null, 2)}\n`,
    '.gitignore': 'node_modules/\ndist/\n.wrangler/\n.dev.vars\n.env*\n!.env.example\n',
    'index.html': '<!doctype html>\n<html lang="en">\n  <head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>SaaS Harness</title></head>\n  <body><div id="root"></div><script type="module" src="/src/react/main.tsx"></script></body>\n</html>\n',
    'vite.config.ts': "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nimport { cloudflare } from '@cloudflare/vite-plugin';\n\nexport default defineConfig({ plugins: [react(), cloudflare()] });\n",
    'tsconfig.json': `${JSON.stringify({ files: [], references: [{ path: './tsconfig.app.json' }, { path: './tsconfig.worker.json' }] }, null, 2)}\n`,
    'tsconfig.app.json': `${JSON.stringify({ compilerOptions: { target: 'ES2022', useDefineForClassFields: true, lib: ['ES2022', 'DOM', 'DOM.Iterable'], allowJs: false, skipLibCheck: true, esModuleInterop: true, allowSyntheticDefaultImports: true, strict: true, forceConsistentCasingInFileNames: true, module: 'ESNext', moduleResolution: 'Bundler', resolveJsonModule: true, isolatedModules: true, noEmit: true, jsx: 'react-jsx' }, include: ['src/react', 'src/generated', 'src/modules'] }, null, 2)}\n`,
    'tsconfig.worker.json': `${JSON.stringify({ compilerOptions: { target: 'ES2022', lib: ['ES2022', 'WebWorker'], module: 'ESNext', moduleResolution: 'Bundler', strict: true, noEmit: true }, include: ['src/worker', 'src/generated', 'src/modules'] }, null, 2)}\n`,
    'wrangler.jsonc': `${JSON.stringify({ $schema: 'node_modules/wrangler/config-schema.json', name: plan.product.name, main: './src/worker/index.ts', compatibility_date: '2025-10-08', compatibility_flags: ['nodejs_compat'], observability: { enabled: true }, upload_source_maps: true, assets: { directory: './dist/client', not_found_handling: 'single-page-application' } }, null, 2)}\n`,
    'src/react/main.tsx': "import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { App } from './App';\nimport './styles.css';\n\ncreateRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);\n",
    'src/react/App.tsx': `import { runtimeConfig } from '../generated/runtime-config';\n\nexport function App() {\n  return (\n    <main className="shell">\n      <p className="eyebrow">Generated by SaaS Harness</p>\n      <h1>${plan.product.name}</h1>\n      <p>Primary journey: <strong>{runtimeConfig.journey}</strong></p>\n      <p>Current feature: <strong>{runtimeConfig.feature.name}</strong></p>\n      {!runtimeConfig.productionReady && <aside role="alert">Provider adapters are not production-ready. Review .saasharness/plan.json.</aside>}\n    </main>\n  );\n}\n`,
    'src/react/styles.css': ':root { font-family: Inter, ui-sans-serif, system-ui, sans-serif; color: #172b4d; background: #f7f8fa; }\nbody { margin: 0; min-width: 320px; }\n.shell { max-width: 52rem; margin: 0 auto; padding: clamp(2rem, 8vw, 7rem) 1.25rem; }\n.eyebrow { text-transform: uppercase; letter-spacing: .12em; font-size: .75rem; }\naside { margin-top: 2rem; padding: 1rem; border: 1px solid #ff5630; border-radius: .75rem; background: #ffebe6; }\n',
    'src/worker/index.ts': "import { Hono } from 'hono';\nimport { runtimeConfig } from '../generated/runtime-config';\n\nconst app = new Hono();\napp.get('/api/health', (context) => context.json({ ok: true, profileHash: runtimeConfig.profileHash, productionReady: runtimeConfig.productionReady }));\nexport default app;\n",
    'src/generated/runtime-config.ts': `export const runtimeConfig = ${tsString({ profileHash: plan.profileHash, productionReady: plan.productionReady, journey: plan.ux.journey, feature: plan.feature, region: plan.product.region, modules: plan.modules, cloudflare: plan.cloudflare })} as const;\n`,
    '.saasharness/plan.json': `${JSON.stringify(plan, null, 2)}\n`,
    'module-lock.json': `${JSON.stringify(plan.moduleLock, null, 2)}\n`,
    'contracts/product.yml': contractRaw.product,
    'contracts/ux.yml': contractRaw.ux,
    'contracts/feature.yml': contractRaw.feature,
    'docs/architecture.md': `# Generated Architecture\n\n- Profile hash: \`${plan.profileHash}\`\n- Region: \`${plan.product.region}\`\n- Database: \`${plan.moduleLock.adapters.database.provider}\`\n- Modules: ${plan.modules.map((module) => `\`${module}\``).join(', ')}\n- Cloudflare services: ${plan.cloudflare.map((service) => `\`${service}\``).join(', ')}\n- Production ready: **${plan.productionReady ? 'yes' : 'no'}**\n\n## Boundaries\n\nProduct features may import module \`public.ts\` files only. Provider SDKs and protected persistence are implementation details.\n\n## Warnings\n\n${plan.warnings.length ? plan.warnings.map((warning) => `- **${warning.code}**: ${warning.message}`).join('\n') : '- None'}\n`,
    'AGENTS.md': '# Generated project rules\n\n1. Work on one feature slice at a time.\n2. Use RED → GREEN → REFACTOR for domain, API, data, auth, billing, permission, and observable React behavior.\n3. Do not import provider SDKs or protected persistence from feature code.\n4. Do not weaken tests to achieve GREEN.\n5. Run risk-routed checks instead of the full suite on every edit.\n6. Production release requires human approval and resolved provider adapters.\n',
    '.github/workflows/ci.yml': "name: ci\non:\n  pull_request:\n  push:\n    branches: [main]\njobs:\n  check:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n          cache: npm\n      - run: npm install\n      - run: npm run check\n      - run: npm test\n",
    'tests/health.test.ts': "import { describe, expect, it } from 'vitest';\nimport worker from '../src/worker';\n\ndescribe('health route', () => {\n  it('returns the generated profile identity', async () => {\n    const response = await worker.request('http://example.test/api/health');\n    expect(response.status).toBe(200);\n    const body = await response.json();\n    expect(body.ok).toBe(true);\n  });\n});\n",
  };

  for (const moduleName of plan.modules) files[`src/modules/${moduleName}/public.ts`] = moduleFile(moduleName);
  if (plan.moduleLock.adapters.database.provider === 'd1') {
    files['migrations/0001_base.sql'] = '-- Generated baseline only; extend through feature TDD.\nCREATE TABLE IF NOT EXISTS app_user (\n  id TEXT PRIMARY KEY,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);\nCREATE TABLE IF NOT EXISTS audit_event (\n  id TEXT PRIMARY KEY,\n  actor_id TEXT,\n  action TEXT NOT NULL,\n  payload_json TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n);\n';
  } else {
    files['migrations/README.md'] = '# PostgreSQL + Hyperdrive\n\nConfigure the external PostgreSQL database and add expand/backfill/contract migrations before production.\n';
  }
  return files;
}
